# log_level = "debug"
log_level = "quiet"

[rocklet]
name = "harmonica"
identifier = "com.github.mcandre.harmonica"
rev = "1"
maintainer = "Andrew Pennebaker <n4jm4@pm.me>"
manufacturer = "YelloSoft"
summary = "comic book repackager"
description = "harmonica repackages comics into batches of smaller collections"
copyright = "Copyright (C) 2023 Andrew Pennebaker"
license = "0BSD"
url = "https://github.com/mcandre/harmonica"

[[pkg]]
image = "n4jm4/rockhopper:0.0.25-macos"
rocklet.oci_arch = "linux/amd64"
rocklet.os_arch = "x86_64"
dest."usr/local/bin" = "bin/harmonica/darwin/amd64"

[[pkg]]
image = "n4jm4/rockhopper:0.0.25-macos"
rocklet.oci_arch = "linux/arm64"
rocklet.os_arch = "arm64"
dest."usr/local/bin" = "bin/harmonica/darwin/arm64"

[[pkg]]
image = "n4jm4/rockhopper:0.0.25-ubuntu"
rocklet.oci_arch = "linux/amd64"
dest."usr/bin" = "bin/harmonica/linux/amd64"

[[pkg]]
image = "n4jm4/rockhopper:0.0.25-ubuntu"
rocklet.oci_arch = "linux/arm64"
dest."usr/bin" = "bin/harmonica/linux/arm64"
